### ISSUE TITLE
discount = 0 for leaf nodes leads to non-smooth predictive distributions

### ISSUE THREAD

**Issue by emaadmanzoor** [balajiln/mondrianforest#5]
For leaf nodes, `max_split_costs` is large, which often leads to `discount = 0` if `discount_parameter` is large (>10). Due to this, predictive distributions at the leaves tend not to be smooth.

For example, the following are the predictive distributions at the leaves when testing with the provided toy dataset and default parameters (for a single tree):

```
pred_prob:
[[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]]
```

Is this the intended behaviour?

**Comment by balajiln** [comment]
Yes, the predictive distribution at the leaf node can be non-smooth if the discount_parameter is large. However, there are two additional levels of smoothing in the prediction from the forest:
(i) the prediction from a tree is a sum of predictions from nodes along the root to leaf node. This is given by equation (7) and described in Alg 8 in the paper.
(ii) the overall prediction from the forest is the average of the predictions from the trees in the forest (described in the paragraph just above Alg 8)
